# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinmyworkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_To_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinmyworkout.Workout_Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinmyworkout.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='event_history',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event_history',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event_History',
        ),
    ]
